"""add budgets table

Revision ID: 4f90bad5cf7e
Revises: fb43a66a8a94
Create Date: 2026-06-25 13:03:20.504460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f90bad5cf7e'
down_revision: Union[str, Sequence[str], None] = 'fb43a66a8a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('materials_amount', sa.Float(), nullable=False),
    sa.Column('labour_amount', sa.Float(), nullable=False),
    sa.Column('contingency_amount', sa.Float(), nullable=False),
    sa.Column('labor_rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_site_id'), 'budgets', ['site_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_site_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
