"""add sites and per-site materials

Revision ID: 6f1ce98f7d01
Revises: c5d246925463
Create Date: 2026-06-06 16:04:04.325135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1ce98f7d01'
down_revision: Union[str, Sequence[str], None] = 'c5d246925463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_industry_id'), 'sites', ['industry_id'], unique=False)

    # Add site_id nullable first so existing rows can be backfilled.
    op.add_column('materials', sa.Column('site_id', sa.Integer(), nullable=True))

    # Data migration: give each industry that already has materials a default "Main
    # Site" and point its materials at it. No-op on a fresh/empty database.
    conn = op.get_bind()
    industry_ids = conn.execute(sa.text("SELECT DISTINCT industry_id FROM materials")).scalars().all()
    for ind_id in industry_ids:
        site_id = conn.execute(
            sa.text(
                "INSERT INTO sites (name, code, is_active, created_at, industry_id) "
                "VALUES ('Main Site', 'MAIN', true, now(), :ind) RETURNING id"
            ),
            {"ind": ind_id},
        ).scalar()
        conn.execute(
            sa.text("UPDATE materials SET site_id = :site WHERE industry_id = :ind"),
            {"site": site_id, "ind": ind_id},
        )

    op.alter_column('materials', 'site_id', nullable=False)
    op.drop_constraint(op.f('uq_material_per_industry'), 'materials', type_='unique')
    op.create_index(op.f('ix_materials_site_id'), 'materials', ['site_id'], unique=False)
    op.create_unique_constraint('uq_material_per_site', 'materials', ['site_id', 'name'])
    op.drop_constraint(op.f('materials_industry_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'sites', ['site_id'], ['id'])
    op.drop_column('materials', 'industry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_industry_id_fkey'), 'materials', 'industries', ['industry_id'], ['id'])
    op.drop_constraint('uq_material_per_site', 'materials', type_='unique')
    op.drop_index(op.f('ix_materials_site_id'), table_name='materials')
    op.create_unique_constraint(op.f('uq_material_per_industry'), 'materials', ['industry_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('materials', 'site_id')
    op.drop_index(op.f('ix_sites_industry_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
