"""add site_image_reports table

Revision ID: d3b379cfd1e8
Revises: 4f90bad5cf7e
Create Date: 2026-06-25 13:48:22.270427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b379cfd1e8'
down_revision: Union[str, Sequence[str], None] = '4f90bad5cf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_image_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=60), nullable=False),
    sa.Column('image_b64', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('progress_estimate', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=False),
    sa.Column('safety_flags', sa.Text(), nullable=False),
    sa.Column('materials_visible', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('used_ai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_image_reports_created_at'), 'site_image_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_site_image_reports_site_id'), 'site_image_reports', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_image_reports_site_id'), table_name='site_image_reports')
    op.drop_index(op.f('ix_site_image_reports_created_at'), table_name='site_image_reports')
    op.drop_table('site_image_reports')
    # ### end Alembic commands ###
