"""site engineer: daily updates and material requests

Revision ID: fb43a66a8a94
Revises: 6f1ce98f7d01
Create Date: 2026-06-06 17:10:43.262061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb43a66a8a94'
down_revision: Union[str, Sequence[str], None] = '6f1ce98f7d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('labor_count', sa.Integer(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('weather_impact', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_updates_created_at'), 'daily_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_updates_site_id'), 'daily_updates', ['site_id'], unique=False)
    op.create_table('material_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'issued', 'rejected', name='requeststatus', native_enum=False), nullable=False),
    sa.Column('needed_for', sa.String(length=160), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requests_created_at'), 'material_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_material_requests_site_id'), 'material_requests', ['site_id'], unique=False)
    op.create_index(op.f('ix_material_requests_status'), 'material_requests', ['status'], unique=False)
    op.create_table('material_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_request_items_request_id'), 'material_request_items', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_request_items_request_id'), table_name='material_request_items')
    op.drop_table('material_request_items')
    op.drop_index(op.f('ix_material_requests_status'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_site_id'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_created_at'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index(op.f('ix_daily_updates_site_id'), table_name='daily_updates')
    op.drop_index(op.f('ix_daily_updates_created_at'), table_name='daily_updates')
    op.drop_table('daily_updates')
    # ### end Alembic commands ###
